/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Logic.ATM;
import Logic.Nasabah;
import javax.swing.JOptionPane;

/**
 *
 * @author nay
 */
public class MenuATMFrame extends FrameDasar{

    
    public MenuATMFrame(Nasabah nasabah) {
        super(nasabah);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ambil_tf = new javax.swing.JButton();
        transfer_tf = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        setor_tf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 27)); // NOI18N
        jLabel1.setText("PILIHAN TRANSAKSI ATM");

        ambil_tf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ambil_tf.setIcon(new javax.swing.ImageIcon("D:\\Kuliah Sem. 3\\DB lanjutan\\money-withdrawal.png")); // NOI18N
        ambil_tf.setText("Tarik");
        ambil_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambil_tfActionPerformed(evt);
            }
        });

        transfer_tf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        transfer_tf.setIcon(new javax.swing.ImageIcon("D:\\Kuliah Sem. 3\\DB lanjutan\\money-transfer (1).png")); // NOI18N
        transfer_tf.setText("Transfer");
        transfer_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_tfActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 160, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Keluar ");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\Kuliah Sem. 3\\DB lanjutan\\benefits.png")); // NOI18N
        jButton4.setText("Info Saldo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setor_tf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setor_tf.setIcon(new javax.swing.ImageIcon("D:\\Kuliah Sem. 3\\DB lanjutan\\bank (1).png")); // NOI18N
        setor_tf.setText("Setor Uang");
        setor_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setor_tfActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(61, 219, 229));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(transfer_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setor_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ambil_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setor_tf)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transfer_tf)
                    .addComponent(ambil_tf))
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ambil_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambil_tfActionPerformed
       int uang = Integer.parseInt(JOptionPane.showInputDialog(rootPane,"Masukan Uang Yang Akan di Tarik","Tarik Tunai",JOptionPane.QUESTION_MESSAGE ));
       this.getAtmControll().withdraw(uang);
       JOptionPane.showMessageDialog(rootPane,"Rp"+this.getAtmControll().checkDeposit(),"Uang Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ambil_tfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.changeFrame(new MenuUtamaFrame());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        JOptionPane.showMessageDialog(rootPane,"RP" +getAtmControll().checkDeposit(),"Ini Saldo Anda ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void transfer_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_tfActionPerformed
       String akun = JOptionPane.showInputDialog(rootPane,"Masukan Nomor Rekening Tujuan","Transfer Uang",JOptionPane.QUESTION_MESSAGE);
       Nasabah nasabah = this.getAtmControll().cekTransfer(akun);
       this.changeFrame(new TransferAtmFrame(nasabah,this.getNasabah()));
    }//GEN-LAST:event_transfer_tfActionPerformed

    private void setor_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setor_tfActionPerformed
       int uang = Integer.parseInt(JOptionPane.showInputDialog(rootPane,"Masukan Setoran Tunai Anda","Setor Tunai",JOptionPane.QUESTION_MESSAGE ));
       this.getAtmControll().saving(uang);
       JOptionPane.showMessageDialog(rootPane,"Rp"+this.getAtmControll().checkDeposit(),"Uang Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_setor_tfActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambil_tf;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setor_tf;
    private javax.swing.JButton transfer_tf;
    // End of variables declaration//GEN-END:variables
}
